apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: devops-tools
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: 1
    defaultRequest:
      memory: 1Gi
      cpu: 1
    type: Container
