apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skopeo-volume
  namespace: jenkins
spec:
  storageClassName: manual      
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
