apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-workspace
  namespace: jenkins
spec:
  storageClassName: manual      
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
