apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loop-pvc
  namespace: devops-tools
spec:
  storageClassName: manual      
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
